pre_release_hook

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -21,12 +21,6 @@ inputs:
       Whether to create a release. Any non-empty value will be treated as true.
       
       Implies `create_tag`.
-  release_notes:
-    description: |
-      The release notes to use for the release. If not provided, release notes will be generated by GitHub's release
-      notes generator.
-      
-      Ignored unless create_release is set.
   tag_prefix:
     description: |
       The prefix to use for the tag. Defaults to `v`.
@@ -37,19 +31,35 @@ inputs:
       
       Set to empty string to disable cause it to error if no previous version can be found.
     default: 0.0.0
-  validate_version:
+  pre_release_hook:
     description: |
-      Command to run to validate the version. If the command exits with a non-zero exit code, the release will be
-      aborted.
+      Command to run before creating the release. You may abort the release by exiting with a non-zero exit code.
       
-      The environment variables `RELEASE_VERSION`, `RELEASE_TAG`, `PREVIOUS_VERSION`, `FIRST_RELEASE` and `GITHUB_TOKEN` 
-      will be set.
+      You may provide custom release notes by writing to the file at `$RELEASE_NOTES_FILE`:
+      ```
+      echo "my release notes" > "$RELEASE_NOTES_FILE"
+      ```
+      
+      The environment variables `RELEASE_VERSION`, `RELEASE_TAG`, `PREVIOUS_VERSION`, `FIRST_RELEASE`, `GITHUB_TOKEN`,
+      and `RELEASE_NOTES_FILE` will be set.
   post_release_hook:
     description: |
       Command to run after the release is complete. 
       
       The environment variables `RELEASE_VERSION`, `RELEASE_TAG`, `PREVIOUS_VERSION`, `FIRST_RELEASE` and `GITHUB_TOKEN` 
       will be set.
+  release_notes:
+    description: |
+      The release notes to use for the release. If not provided, release notes will be generated by GitHub's release
+      notes generator.
+
+      Ignored unless create_release is set.
+    deprecationMessage: |
+      Use `pre_release_hook` instead.
+  validate_version:
+    description: Alias for `pre_release_hook`.
+    deprecationMessage: |
+      Use `pre_release_hook` instead.
 outputs:
   previous_ref:
     value: ${{ steps.prev.outputs.ref }}
@@ -74,27 +84,41 @@ outputs:
 runs:
   using: composite
   steps:
-    - name: check repo
+    - id: init
       shell: sh
       working-directory: ${{ inputs.checkout_dir }}
+      env:
+        VALIDATE_VERSION: ${{ inputs.validate_version }}
+        PRE_RELEASE_HOOK: ${{ inputs.pre_release_hook }}
+        RELEASE_NOTES: ${{ inputs.release_notes }}
       run: |
         if [ "$(git rev-parse --is-shallow-repository)" = "true" ]; then
           echo "fatal: shallow clones are not supported" >&2
           exit 1
         fi
-    - name: get previous tag
+        if [ -n "$VALIDATE_VERSION" ] && [ -n "$PRE_RELEASE_HOOK" ]; then
+          echo "fatal: cannot specify both validate_version and pre_release_hook" >&2
+          exit 1
+        fi
+        PRE_RELEASE_HOOK_FILE="${{ runner.temp }}/pre_release_hook-${{ github.run_id }}-${{ github.run_attempt }}"
+        echo "${PRE_RELEASE_HOOK}${VALIDATE_VERSION}" > "$PRE_RELEASE_HOOK_FILE"
+        echo "pre_release_hook_file=$PRE_RELEASE_HOOK_FILE" > "$GITHUB_OUTPUT"
+        
+        RELEASE_NOTES_FILE="${{ runner.temp }}/release_notes-${{ github.run_id }}-${{ github.run_attempt }}"
+        echo "$RELEASE_NOTES" > "$RELEASE_NOTES_FILE"
+        echo "release_notes_file=$RELEASE_NOTES_FILE" >> "$GITHUB_OUTPUT"
+    - id: prev
       shell: sh
-      id: prev
+      working-directory: ${{ inputs.checkout_dir }}
       env:
         REF: ${{ inputs.ref }}
         TAG_PREFIX: ${{ inputs.tag_prefix }}
         DEFAULT_PREVIOUS_VERSION: ${{ inputs.default_previous_version }}
-      working-directory: ${{ inputs.checkout_dir }}
       run: |
         "${{ github.action_path }}"/script/prev > $GITHUB_OUTPUT
-    - name: get next tag
+    - id: next
       shell: sh
-      id: next
+      working-directory: ${{ inputs.checkout_dir }}
       env:
         PREVIOUS_VERSION: ${{ steps.prev.outputs.version }}
         PREVIOUS_TAG: ${{ steps.prev.outputs.ref }}
@@ -103,11 +127,10 @@ runs:
         REPO: ${{ github.repository }}
         TAG_PREFIX: ${{ inputs.tag_prefix }}
         GITHUB_TOKEN: ${{ inputs.github_token }}
-      working-directory: ${{ inputs.checkout_dir }}
       run: |
         "${{ github.action_path }}"/script/next > $GITHUB_OUTPUT
-    - name: validate
-      if: ${{ steps.next.outputs.release_version != '' && steps.next.outputs.release_tag != ''  && inputs.validate_version != '' }}
+    - name: pre release hook
+      if: ${{ steps.next.outputs.release_version != '' && steps.next.outputs.release_tag != '' }}
       shell: sh
       working-directory: ${{ inputs.checkout_dir }}
       env:
@@ -116,7 +139,11 @@ runs:
         PREVIOUS_VERSION: ${{ steps.prev.outputs.version }}
         FIRST_RELEASE: ${{ steps.prev.outputs.first_release }}
         GITHUB_TOKEN: ${{ inputs.github_token }}
-      run: ${{ inputs.validate_version }}
+        RELEASE_NOTES_FILE: ${{ steps.init.outputs.release_notes_file }}
+        PRE_RELEASE_HOOK_FILE: ${{ steps.init.outputs.pre_release_hook_file }}
+      run: |
+        chmod +x "${{ steps.init.outputs.pre_release_hook_file }}"
+        "${{ steps.init.outputs.pre_release_hook_file }}"
     - name: create release
       shell: sh
       if: ${{ steps.next.outputs.release_version != '' && steps.next.outputs.release_tag != '' }}
@@ -124,7 +151,7 @@ runs:
       env:
         CREATE_TAG: ${{ inputs.create_tag }}
         CREATE_RELEASE: ${{ inputs.create_release }}
-        RELEASE_NOTES: ${{ inputs.release_notes }}
+        RELEASE_NOTES_FILE: ${{ steps.init.outputs.release_notes_file }}
         RELEASE_TAG: ${{ steps.next.outputs.release_tag }}
         PREVIOUS_TAG: ${{ steps.prev.outputs.ref }}
         REF: ${{ inputs.ref }}
@@ -137,9 +164,9 @@ runs:
       if: ${{ steps.next.outputs.release_version != '' && steps.next.outputs.release_tag != '' && inputs.post_release_hook != '' }}
       working-directory: ${{ inputs.checkout_dir }}
       env:
-          RELEASE_VERSION: ${{ steps.next.outputs.release_version }}
-          RELEASE_TAG: ${{ steps.next.outputs.release_tag }}
-          PREVIOUS_VERSION: ${{ steps.prev.outputs.version }}
-          FIRST_RELEASE: ${{ steps.prev.outputs.first_release }}
-          GITHUB_TOKEN: ${{ inputs.github_token }}
+        RELEASE_VERSION: ${{ steps.next.outputs.release_version }}
+        RELEASE_TAG: ${{ steps.next.outputs.release_tag }}
+        PREVIOUS_VERSION: ${{ steps.prev.outputs.version }}
+        FIRST_RELEASE: ${{ steps.prev.outputs.first_release }}
+        GITHUB_TOKEN: ${{ inputs.github_token }}
       run: ${{ inputs.post_release_hook }}
